trigger:
  branches:
    include:
      - dev # Trigger on changes to the main branch (or any branch you prefer)
resources:
  pipelines:
    - pipeline: pull-push-image
      source: 'pull-push-image'
      trigger: true

pool:
  vmImage: 'ubuntu-latest' # Use a VM to run the steps

variables:
- group: variable_group

steps:
  # Step 1: Checkout the Bicep file from GitHub
  - checkout: self
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'az-resource-manager' # Use the Azure Service connection
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create --name newResourceGroup --location eastus
        az deployment group create \
          --resource-group newResourceGroup \
          --template-file deploy.bicep \
          --parameters containerGroupName=$(containerGroupName) containerName=$(containerName )
      workingDirectory: $(System.DefaultWorkingDirectory)
