trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_NAME: rkvarma4518/pdfhub:latest
  TRIVY_CACHE_DIR: /opt/trivy-cache
  REPORT_DIR: $(Build.SourcesDirectory)/trivy-report
  REPORT_FILE: trivy-full-report.html

steps:

# Pull image
- script: |
    docker pull $(IMAGE_NAME)
  displayName: Pull Docker Image

# Prepare report directory
- script: |
    mkdir -p $(REPORT_DIR)
  displayName: Prepare report directory

# Download Trivy DB (one-time cache)
- script: |
    if [ ! -d "$(TRIVY_CACHE_DIR)/db" ]; then
      docker run --rm \
        -v $(TRIVY_CACHE_DIR):/root/.cache/ \
        aquasec/trivy:0.49.1 \
        image --download-db-only
    else
      echo "Trivy DB already present"
    fi
  displayName: Download Trivy DB

# OFFLINE Scan + FULL HTML Report
- script: |
    docker run --rm \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v $(TRIVY_CACHE_DIR):/root/.cache/ \
      -v $(REPORT_DIR):/report \
      aquasec/trivy:0.49.1 image \
      --offline-scan \
      --skip-db-update \
      --scanners vuln,secret \
      --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
      --ignore-unfixed \
      --format template \
      --template "@/contrib/html.tpl" \
      -o /report/$(REPORT_FILE) \
      $(IMAGE_NAME)
  displayName: Trivy Offline Scan (Full HTML Report)

# Publish HTML report
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(REPORT_DIR)'
    artifactName: 'Trivy-Vulnerability-Report'
  displayName: Publish Trivy HTML Report
