trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: variable_group  # This group must include azure_registry, ACRServiceConnection

# List of 5 public DockerHub images
- name: dockerHubImages
  value: |
    openjdk:21-jdk-slim
    ubuntu:22.04

# Repository name in ACR where all images will be pushed
- name: acrRepository
  value: apprepo

steps:
# Step 1: Login to Azure Container Registry (ACR)
- task: Docker@2
  inputs:
    containerRegistry: '$(ACRServiceConnection)'
    command: 'login'
  displayName: 'Login to ACR'

# Step 2: Pull images from Docker Hub
- script: |
    echo "Pulling Docker Hub images..."
    echo "$(dockerHubImages)" | while read image; do
      if [ -n "$image" ]; then
        docker pull $image
      fi
    done
  displayName: 'Pull 5 Public Images from Docker Hub'

# Step 3: Tag images to push into ACR under a single repo with different tags
- script: |
    echo "Tagging images for ACR single repository '$(acrRepository)'..."
    count=1
    echo "$(dockerHubImages)" | while read image; do
      if [ -n "$image" ]; then
        tagName=qa.2$count
        docker tag $image $(azure_registry).azurecr.io/$(acrRepository):$tagName
        count=$((count + 1))
      fi
    done
    docker images
  displayName: 'Tag Images for ACR'

# Step 4: Push tagged images to ACR
- script: |
    echo "Pushing images to ACR repository '$(acrRepository)'..."
    count=1
    echo "$(dockerHubImages)" | while read image; do
      if [ -n "$image" ]; then
        tagName=qa.2$count
        docker push $(azure_registry).azurecr.io/$(acrRepository):$tagName
        count=$((count + 1))
      fi
    done
  displayName: 'Push Images to ACR with Different Tags'
