trigger:
- none

pr:
- none

resources:
  repositories:
  - repository: resourceRepo
    type: github
    name: rkvarma1845/Hear-Check
    ref: main
    endpoint: 'github connection 1'

variables:
  advancedsecurity.codeql.language: python

pool:
  vmImage: ubuntu-latest

steps:
- checkout: resourceRepo
  clean: true

# 2️⃣ Initialize CodeQL (SETS languages internally)
- task: AdvancedSecurity-Codeql-Init@1
  displayName: Initialize CodeQL

# 3️⃣ Run CodeQL analysis (AUTO publishes to Security tab)
- task: AdvancedSecurity-Codeql-Analyze@1
  displayName: Run CodeQL Analysis
