trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: variable_group

steps:
- task: AzureCLI@2
  displayName: Cleanup ACR Images
  inputs:
    azureSubscription: '$(azure_subscription_connection)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "🧹 Starting cleanup for ACR: $(azure_registry)"
      echo "Fetching repositories"
      # repositories=$(az acr repository list --name '$(azure_registry)' --output tsv)
      # echo "$repositories"
      # echo ""

      IFS=',' read -ra repos <<< "$(cleanupRepos)"
      # IFS=',' read -ra repos <<< "$(cleanupRepos)"

      for repo in "${repos[@]}"; do
        echo "📦 Processing repository : $repo"

        images=$(az acr repository show-manifests \
          --name '$(azure_registry)' \
          --repository $repo \
          --output json)

        sorted_images=$(echo "$images" | jq 'sort_by(.timestamp) | reverse')
        total=$(echo "$sorted_images" | jq length)

        echo ""
        echo "🔢 Total images : $total"
        echo ""
        echo "All Images (digest timestamp tags): "
        echo "$sorted_images" | jq -r '.[] | "\(.digest) \(.timestamp) \(.tags | if length > 0 then join(",") else "No_tag" end)"'
        echo ""

        tags_to_delete=$(az acr repository show-tags \
          --name $(azure_registry) \
          --repository $repo \
          --detail)


        echo "$tags_to_delete"


        # if (( total > 3 )); then
          # digests_to_delete=$(echo "$sorted_images" | jq -r '.[3:][] | .digest')
          # digests_to_delete=$(echo "$sorted_images" | jq -r '
          #   .[] |
          #   {
          #     digest: .digest,
          #     ts: .timestamp,
          #     group:
          #       (if (.tags | any(startswith("qa."))) then "qa"
          #       elif (.tags | any(startswith("prod."))) then "prod"
          #       else "other"
          #       end)
          #   } |
          #   [.group, .digest] | @tsv
          # ' | awk '
          # {
          #   group=$1
          #   digest=$2

          #   if (!seen[digest]++) {
          #     count[group]++
          #     if (count[group] > 3)
          #       print digest
          #   }
          # }')

          # echo "$digests_to_delete"
          # for digest in $digests_to_delete; do
            # echo "🗑️ Deleting image digest: $digest"
            # az acr repository delete --name "$(azure_registry)" --image "$repo@$digest" --yes 2>&1 | grep -v "^WARNING"
          # done
          
          # images=$(az acr repository show-manifests \
          #   --name '$(azure_registry)' \
          #   --repository $repo \
          #   --output json)
          # sorted_images=$(echo "$images" | jq 'sort_by(.timestamp) | reverse')
          # echo ""
          # echo "Remaining 3 Images (digest timestamp tags):"
          # echo "$sorted_images" | jq -r '.[] | "\(.digest) \(.timestamp) \(.tags | if length > 0 then join(",") else "No_tag" end)"'
          # echo ""

        # else
        #   echo "✅ Nothing to delete. Only $total image(s) exist in $repo."
        # fi
      done

      echo "🎉 Cleanup complete for all repositories!"
      echo ""

