trigger: none

pr: none

resources:
  repositories:
    - repository: SourceRepo
      type: github
      name: rkvarma1845/Hear-Check
      ref: refs/heads/main
      endpoint: 'github connection 1'

steps:
- checkout: SourceRepo
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install bandit
    bandit -r . -f sarif -o bandit.sarif
  displayName: Run Bandit Scan

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: bandit.sarif
    artifactName: SecurityReports