trigger: none
pr: none

resources:
  pipelines:
  - pipeline: build
    source: ci-build
    trigger: true

pool:
  vmImage: ubuntu-latest

jobs:
- job: DeployJob
  variables:
    imageTagFromBuild: $[ resources.pipeline.build.outputs['BuildStage.BuildJob.setVersion.imageTag'] ]
  steps:
  - bash: |
      echo "Received image tag: $(imageTagFromBuild)"