trigger:
- none

pr:
- none

resources:
  repositories:
  - repository: resourceRepo
    type: github
    name: rkvarma1845/Hear-Check
    ref: main
    endpoint: 'github connection 1'

  - repository: targetRepo
    type: git
    name: dep-docker-image/dep-docker-image

variables:
  advancedsecurity.codeql.language: python
  GITHUB_REPO_PATH: $(Build.SourcesDirectory)/resourceRepo
  github_pat: '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'

pool:
  vmImage: ubuntu-latest

steps:
# 1️⃣ Checkout GitHub repo to a known path
- checkout: resourceRepo
  clean: true
  path: github-src

# 2️⃣ Mirror push to Azure Repo
- task: Bash@3
  displayName: "Clone GitHub repo and push branch"
  env:
    GITHUB_TOKEN: $(github_pat)
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    targetType: 'inline'
    script: |
      git clone https://${GITHUB_TOKEN}@github.com/rkvarma1845/Hear-Check.git
      cd Hear-Check

      git checkout main

      git remote add mirror https://rkvarma4518@dev.azure.com/rkvarma4518/dep-docker-image/_git/dep-docker-image

      git config --global http.https://dev.azure.com/.extraheader "AUTHORIZATION: bearer PXStDt20Sl1qigV8OgwM5OS0nNTCBzdJZZIQl6x7g1qsZGGXbDWXJQQJ99CAACAAAAAAAAAAAAASAZDO2OmX"
      git push mirror main -f




# 3️⃣ Checkout Azure Repo for analysis
- checkout: targetRepo

# 4️⃣ Initialize CodeQL
- task: AdvancedSecurity-Codeql-Init@1
  displayName: Initialize CodeQL

# 5️⃣ Run CodeQL analysis and publish results to Security tab
- task: AdvancedSecurity-Codeql-Analyze@1
  displayName: Run CodeQL Analysis
