trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

variables:
  CODEQL_VERSION: '2.16.4'
  GITHUB_PAT: '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'   # reference secret variable


resources:
  repositories:
  - repository: resourceRepo
    type: github
    name: rkvarma4518/linkpeek
    ref: main
    endpoint: 'github connection 1'


steps:
- checkout: resourceRepo

# -------------------------
# Install CodeQL
# -------------------------
- task: Bash@3
  displayName: Install CodeQL
  inputs:
    targetType: inline
    script: |
      CODEQL_VERSION=2.16.4

      wget https://github.com/github/codeql-cli-binaries/releases/download/v${CODEQL_VERSION}/codeql-linux64.zip
      unzip codeql-linux64.zip

      export PATH=$PATH:$(pwd)/codeql
      echo "##vso[task.setvariable variable=PATH]$PATH"

      codeql version

# Clone official query packs
- task: Bash@3
  displayName: Install Python Query Pack
  inputs:
    targetType: inline
    script: |
      codeql pack init codeql/python-queries
      # ls -R   
      cd python-queries/
      codeql pack install

# -------------------------
# Create CodeQL Database
# -------------------------
- task: Bash@3
  displayName: Create CodeQL Database
  inputs:
    targetType: inline
    script: |
      cd $(Build.SourcesDirectory)
      codeql database create codeql-db \
        --language=python \
        --source-root=.

# -------------------------
# Analyze Code
# -------------------------

- task: Bash@3
  displayName: Run CodeQL Analysis
  inputs:
    targetType: inline
    script: |
      cd $(Build.SourcesDirectory)
      codeql database analyze codeql-db \
        --format=sarifv2.1.0 \
        --output=codeql-results.sarif \


# -------------------------
# Publish Results
# -------------------------
- task: PublishBuildArtifacts@1
  displayName: Publish CodeQL Report
  inputs:
    pathToPublish: codeql-results.sarif
    artifactName: CodeQL-Report

- script: |
    set -e

    echo "Base64 encoding SARIF..."
    base64 codeql-results.sarif > sarif.b64

    echo "Creating upload payload..."
    jq -n \
      --rawfile sarif sarif.b64 \
      --arg sha "$(Build.SourceVersion)" \
      --arg ref "refs/heads/$(Build.SourceBranchName)" \
      '{
        commit_sha: $sha,
        ref: $ref,
        sarif: $sarif
      }' > upload.json

    echo "Uploading SARIF to GitHub..."
    curl -sSf -X POST \
      -H "Authorization: Bearer $(GITHUB_PAT)" \
      -H "Accept: application/vnd.github+json" \
      https://api.github.com/repos/rkvarma4518/HearCheck/code-scanning/sarifs \
      --data-binary @upload.json
  displayName: 'Upload SARIF to GitHub Code Scanning'

