trigger: none

pr: none

resources:
  repositories:
    - repository: SourceRepo
      type: github
      name: rkvarma1845/Hear-Check
      ref: refs/heads/main
      endpoint: 'github connection 1'

steps:
- checkout: SourceRepo
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    pip install bandit
    bandit -r . -f json -o bandit.json --exit-zero
  displayName: Run Bandit Scan

- script: |
    python - <<EOF
    import json, sys
    with open("bandit.json") as f:
        data = json.load(f)

    high = [i for i in data["results"] if i["issue_severity"] in ("HIGH", "MEDIUM")]

    if high:
        print(f"❌ Security issues found: {len(high)}")
        sys.exit(1)
    else:
        print("✅ No high/medium issues")
    EOF
  displayName: Fail on High/Medium