trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Deploy resources using the existing resource group
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-resource'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --resource-group deploy \
        --template-file deploy.bicep \
        --parameters \
          acrName=depdocker \
          appServicePlanName=myAppServicePlan \
          webAppName=myWebApp \
          imageName=hello-world \
          imageTag=latest
    addSpnToEnvironment: true

# Optionally, test the deployment result by querying resources
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-resource'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp show --name myWebApp --resource-group deploy
    addSpnToEnvironment: true
