trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

variables:
  CODEQL_VERSION: '2.16.4'

resources:
  repositories:
  - repository: resourceRepo
    type: github
    name: rkvarma4518/linkpeek
    ref: main
    endpoint: 'github connection 1'


steps:
- checkout: resourceRepo

# -------------------------
# Install CodeQL
# -------------------------
- task: Bash@3
  displayName: Install CodeQL
  inputs:
    targetType: inline
    script: |
      CODEQL_VERSION=2.16.4

      wget https://github.com/github/codeql-cli-binaries/releases/download/v${CODEQL_VERSION}/codeql-linux64.zip
      unzip codeql-linux64.zip

      export PATH=$PATH:$(pwd)/codeql
      echo "##vso[task.setvariable variable=PATH]$PATH"

      codeql version

# Clone official query packs
- task: Bash@3
  displayName: Install Python Query Pack
  inputs:
    targetType: inline
    script: |
      codeql pack init codeql/python-queries
      # ls -R   
      cd python-queries/
      codeql pack install

# -------------------------
# Create CodeQL Database
# -------------------------
- task: Bash@3
  displayName: Create CodeQL Database
  inputs:
    targetType: inline
    script: |
      cd $(Build.SourcesDirectory)
      codeql database create codeql-db \
        --language=python \
        --source-root=.

# -------------------------
# Analyze Code
# -------------------------

- task: Bash@3
  displayName: Run CodeQL Analysis
  inputs:
    targetType: inline
    script: |
      cd $(Build.SourcesDirectory)
      codeql database analyze codeql-db \
        --format=sarifv2.1.0 \
        --output=codeql-results.sarif \


# -------------------------
# Publish Results
# -------------------------
- task: PublishBuildArtifacts@1
  displayName: Publish CodeQL Report
  inputs:
    pathToPublish: codeql-results.sarif
    artifactName: CodeQL-Report


- task: AdvancedSecurity-Publish@1
  inputs:
    EnableRecursiveScanning: true
    WaitForProcessing: true
    WaitForProcessingTimeout: 120

