trigger:
- none

pr:
- none

resources:
  repositories:
  - repository: resourceRepo
    type: github
    name: rkvarma1845/Hear-Check
    ref: main
    endpoint: 'github connection 1'

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_PAT: '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'   # reference secret variable
  CODEQL_VERSION: '2.16.1'
  GITHUB_REPO: 'rkvarma1845/Hear-Check'   # <-- change this
  GITHUB_REF: 'refs/heads/main'

steps:
- checkout: resourceRepo

# 1️⃣ Download CodeQL
- bash: |
    wget https://github.com/github/codeql-cli-binaries/releases/download/v$(CODEQL_VERSION)/codeql-linux64.zip
    unzip codeql-linux64.zip
    chmod +x codeql/codeql
  displayName: Download CodeQL CLI


# 2️⃣ Create CodeQL Database
- bash: |
    ./codeql/codeql database create codeql-db \
      --language=python \
      --source-root .
  displayName: Create CodeQL Database

# # 3️⃣ Analyze
# - bash: |
#     ./codeql/codeql database analyze codeql-db \
#       codeql/python-queries \
#       --format=sarifv2 \
#       --output=codeql-results.sarif
#   displayName: Run CodeQL Analysis

- bash: |
    ./codeql/codeql database analyze codeql-db \
      --download \
      codeql/python-all \
      --format=sarifv2 \
      --output=codeql-results.sarif
  displayName: Run CodeQL Analysis



# -------------------------
# Upload SARIF to GitHub
# -------------------------
- bash: |
    ./codeql/codeql github upload-results \
      --repository $(GITHUB_REPO) \
      --ref $(GITHUB_REF) \
      --commit $(Build.SourceVersion) \
      --sarif codeql-results.sarif \
      --github-auth $GITHUB_PAT
  displayName: Upload CodeQL Results to GitHub
  env:
    GITHUB_PAT: $(GITHUB_PAT)

# 4️⃣ Publish SARIF
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: codeql-results.sarif
    artifactName: CodeQL-Results
