trigger:
- none

pr:
- none

resources:
  repositories:
  - repository: resourceRepo
    type: github
    name: rkvarma1845/Hear-Check
    ref: main
    endpoint: 'github connection 1'

variables:
  advancedsecurity.codeql.language: python
  AZURE_REPO_URL: https://rkvarma4518@dev.azure.com/rkvarma4518/dep-docker-image/_git/dep-docker-image
  GITHUB_REPO_PATH: $(Build.SourcesDirectory)/resourceRepo

pool:
  vmImage: ubuntu-latest

steps:
# 1️⃣ Checkout GitHub repo to a known path
- checkout: resourceRepo
  clean: true
  path: github-src

# 2️⃣ Mirror push to Azure Repo
# - script: |
#     git config --global user.name "AzurePipeline"
#     git config --global user.email "pipeline@azure.com"

#     cd $(Build.SourcesDirectory)/github-src
#     git remote add azure $(AZURE_REPO_URL) || echo "Remote exists"
#     git push azure HEAD:refs/heads/main --force
#   displayName: Mirror GitHub to Azure Repo

- task: Mirror-Repositories@1
  inputs:
    sourceType: true
    sourceURL: 'https://github.com/nevincansel/mirror-repositories-test.git'
    sourcePAT: '$(github_pat)'
    destinationType: true
    destinationURL: 'https://dev.azure.com/nevincansel5517/MyWorks/_git/mirror-test'
    destinationPAT: '$(azure_pat)'



# 3️⃣ Checkout mirrored Azure Repo for analysis
- checkout: self
  clean: true
  displayName: Checkout Azure Repo

# 4️⃣ Initialize CodeQL
- task: AdvancedSecurity-Codeql-Init@1
  displayName: Initialize CodeQL

# 5️⃣ Run CodeQL analysis and publish results to Security tab
- task: AdvancedSecurity-Codeql-Analyze@1
  displayName: Run CodeQL Analysis
