trigger:
- none

pr:
- none

resources:
  repositories:
  - repository: resourceRepo
    type: github
    name: rkvarma1845/Hear-Check
    ref: main
    endpoint: 'github connection 1'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: resourceRepo

# Download CodeQL
- bash: |
    # wget https://github.com/github/codeql-cli-binaries/releases/download/v2.16.1/codeql-linux64.zip
    wget https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip
    unzip codeql-linux64.zip
    chmod +x codeql/codeql
    ./codeql/codeql version
  displayName: Download CodeQL CLI


# Create CodeQL Database
- bash: |
    ./codeql/codeql database create codeql-db \
      --language=python \
      --source-root .
  displayName: Create CodeQL Database

# Analyze
- bash: |
    ./codeql/codeql database analyze codeql-db \
      --download \
      codeql/python-queries \
      --format=sarifv2.1.0 \
      --output=codeql-results.sarif
  displayName: Run CodeQL Analysis

# Publish SARIF
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: codeql-results.sarif
    artifactName: CodeQL-Results
