trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Run deploy-main.yml only when branch = dev
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
    - template: deploy-main.yml
