trigger: none


variables:
  - name: variableGroupName
    value: 'none'

  # Conditional variable groups
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    - group: variable_group
    - name: variableGroupName
      value: 'variable_group'

  - ${{ if eq(variables['Build.SourceBranchName'], 'qa') }}:
    - group: variable_group - Copy
    - name: variableGroupName
      value: 'variable_group - Copy'

stages:
- stage: Build
  displayName: "Conditional Variable Example"
  jobs:
  - job: PrintVars
    displayName: "Print Selected Variables"
    steps:
    - script: |
        echo "Branch Name: $(Build.SourceBranchName)"
        echo "Variable Group Name: $(variableGroupName)"
        echo "ACRServiceConnection Name: $(ACRServiceConnection)"
        echo "Variable Group Applied Successfully"
      displayName: "Show Selected Variables"
