trigger: none


variables:
  - group: SP Details

steps:
- task: AzureCLI@2
  displayName: 'Deploy Bicep with Array Input'
  inputs:
    azureSubscription: 'az-resource-manager'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Deploying Bicep file with array input..."
      az deployment group create \
        --verbose \
        --resource-group azure-devops \
        --template-file sp.bicep \
        --parameters sp_details="$sp_detail"
        # --query "properties.outputs" -o json

      echo "Bicep deployment completed!"
