trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildStage
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "Setting version variable"
        echo "##vso[task.setvariable variable=imageTag;isOutput=true]v1.2.0"
      name: setVersion