trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- bash: echo "v1.2.0" > $(Build.ArtifactStagingDirectory)/imageTag.txt

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)/imageTag.txt
    artifact: build1ImageTag